// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller.js"
application.register("address-autocomplete", AddressAutocompleteController)

import ChallengeController from "./challenge_controller.js"
application.register("challenge", ChallengeController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MapChallengeController from "./map_challenge_controller.js"
application.register("map-challenge", MapChallengeController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import MapMobileController from "./map_mobile_controller.js"
application.register("map-mobile", MapMobileController)
